///|
pub extend FunctionProvenanceError with Debug::{to_repr}

///|
pub extend FunctionProvenanceError with Eq::{not_equal, equal}

///|
pub extend PhysicalFunctionOrigin with Debug::{to_repr}

///|
pub extend PhysicalFunctionOrigin with Eq::{not_equal, equal}

///|
pub extend PhysicalFunctionProvenance with Debug::{to_repr}

///|
pub extend PhysicalFunctionProvenance with Eq::{not_equal, equal}

///|
pub extend PhysicalLoweringError with Debug::{to_repr}

///|
pub extend PhysicalLoweringError with Eq::{not_equal, equal}

///|
pub extend PhysicalLoweringProvenance with Debug::{to_repr}

///|
pub extend PhysicalLoweringProvenance with Eq::{not_equal, equal}
