///|
pub extend WasmCompileError with Debug::{to_repr}

///|
pub extend WasmCompileError with Eq::{not_equal, equal}

///|
pub extend WasmCompileObservation with Debug::{to_repr}

///|
pub extend WasmFunctionOrigin with Debug::{to_repr}

///|
pub extend WasmFunctionOrigin with Eq::{not_equal, equal}

///|
pub extend WasmBuiltinFunctionRole with Debug::{to_repr}

///|
pub extend WasmBuiltinFunctionRole with Eq::{not_equal, equal}

///|
pub extend WasmFunctionProvenance with Debug::{to_repr}

///|
pub extend WasmFunctionProvenance with Eq::{not_equal, equal}

///|
pub extend WasmFunctionScale with Debug::{to_repr}

///|
pub extend WasmFunctionScale with Eq::{not_equal, equal}

///|
pub extend WasmPhysicalOpcodeFamily with Debug::{to_repr}

///|
pub extend WasmPhysicalOpcodeFamily with Eq::{not_equal, equal}

///|
pub extend WasmExpansionCategory with Debug::{to_repr}

///|
pub extend WasmExpansionCategory with Eq::{not_equal, equal}

///|
pub extend WasmExpansionScale with Debug::{to_repr}

///|
pub extend WasmExpansionScale with Eq::{not_equal, equal}

///|
pub extend WasmHelperFunctionRole with Debug::{to_repr}

///|
pub extend WasmHelperFunctionRole with Eq::{not_equal, equal}

///|
pub extend WasmModuleScale with Debug::{to_repr}

///|
pub extend WasmModuleScale with Eq::{not_equal, equal}

///|
pub extend WasmRuntimeFunctionRole with Debug::{to_repr}

///|
pub extend WasmRuntimeFunctionRole with Eq::{not_equal, equal}
