///|
pub extend CompilationFailure with Debug::{to_repr}

///|
pub extend CompilationFailure with Eq::{not_equal, equal}

///|
pub extend CompilationOutcome with Debug::{to_repr}

///|
pub extend CompilationOutcome with Eq::{not_equal, equal}

///|
pub extend CompilationRequest with Debug::{to_repr}

///|
pub extend CompilationRequest with Eq::{not_equal, equal}

///|
pub extend CompilationStageScale with Debug::{to_repr}

///|
pub extend CompilationStageScale with Eq::{not_equal, equal}

///|
pub extend CompilationStageSnapshot with Debug::{to_repr}

///|
pub extend CompilationStageSnapshot with Eq::{not_equal, equal}

///|
pub extend CompilationWarnings with Debug::{to_repr}

///|
pub extend CompilationWarnings with Eq::{not_equal, equal}

///|
pub extend CompiledEntry with Debug::{to_repr}

///|
pub extend CompiledEntry with Eq::{not_equal, equal}

///|
pub extend CompiledModules with Debug::{to_repr}

///|
pub extend CompiledModules with Eq::{not_equal, equal}

///|
pub extend CompiledProgram with Debug::{to_repr}

///|
pub extend CompiledProgram with Eq::{not_equal, equal}

///|
pub extend InterfaceCompilationRequest with Debug::{to_repr}

///|
pub extend InterfaceCompilationRequest with Eq::{not_equal, equal}

///|
pub extend SourceCompilationStage with Debug::{to_repr}

///|
pub extend SourceCompilationStage with Eq::{not_equal, equal}

///|
pub extend SourceStageScale with Debug::{to_repr}

///|
pub extend SourceStageScale with Eq::{not_equal, equal}
