///|
pub extend SourceDatabase with Debug::{to_repr}

///|
pub extend SourceDatabase with Eq::{not_equal, equal}

///|
pub extend SourceFile with Debug::{to_repr}

///|
pub extend SourceFile with Eq::{not_equal, equal}

///|
pub extend SourcePosition with Debug::{to_repr}

///|
pub extend SourcePosition with Eq::{not_equal, equal}

///|
pub extend SourceRange with Debug::{to_repr}

///|
pub extend SourceRange with Eq::{not_equal, equal}
