///|
pub extend ArcFinalBodyError with Debug::{to_repr}

///|
pub extend ArcFinalBodyError with Eq::{not_equal, equal}

///|
pub extend Block with Debug::{to_repr}

///|
pub extend Block with Eq::{not_equal, equal}

///|
pub extend Edge with Debug::{to_repr}

///|
pub extend Edge with Eq::{not_equal, equal}

///|
pub extend FinalizeError with Debug::{to_repr}

///|
pub extend FinalizeError with Eq::{not_equal, equal}

///|
pub extend FunctionBody with Debug::{to_repr}

///|
pub extend FunctionBody with Eq::{not_equal, equal}

///|
pub extend FunctionEntry with Debug::{to_repr}

///|
pub extend FunctionEntry with Eq::{not_equal, equal}

///|
pub extend FunctionInputs with Debug::{to_repr}

///|
pub extend FunctionInputs with Eq::{not_equal, equal}

///|
pub extend FunctionTableCanonicalizationError with Debug::{to_repr}

///|
pub extend FunctionTableCanonicalizationError with Eq::{not_equal, equal}

///|
pub extend Image with @prettyprinter.Pretty::{pretty}

///|
pub extend Image with Debug::{to_repr}

///|
pub extend Image with Eq::{not_equal, equal}

///|
pub extend Instruction with Debug::{to_repr}

///|
pub extend Instruction with Eq::{not_equal, equal}

///|
pub extend LayoutOperand with Debug::{to_repr}

///|
pub extend LayoutOperand with Eq::{not_equal, equal}

///|
pub extend Ownership with Debug::{to_repr}

///|
pub extend Ownership with Eq::{not_equal, equal}

///|
pub extend PhysicalSlotPlanError with Debug::{to_repr}

///|
pub extend PhysicalSlotPlanError with Eq::{not_equal, equal}

///|
pub extend ProjectionResult with Debug::{to_repr}

///|
pub extend ProjectionResult with Eq::{not_equal, equal}

///|
pub extend ProjectionSelection with Debug::{to_repr}

///|
pub extend ProjectionSelection with Eq::{not_equal, equal}

///|
pub extend Terminator with Debug::{to_repr}

///|
pub extend Terminator with Eq::{not_equal, equal}

///|
pub extend UseDefAnalysisError with Debug::{to_repr}

///|
pub extend UseDefAnalysisError with Eq::{not_equal, equal}

///|
pub extend ValueDefinitionSite with Debug::{to_repr}

///|
pub extend ValueDefinitionSite with Eq::{not_equal, equal}

///|
pub extend ValueId with Compare::{op_lt, op_le, op_ge, compare, op_gt}

///|
pub extend ValueId with Debug::{to_repr}

///|
pub extend ValueId with Eq::{not_equal, equal}

///|
pub extend ValueMetadata with Debug::{to_repr}

///|
pub extend ValueMetadata with Eq::{not_equal, equal}
