///|
pub extend DeclarationIdentities with Debug::{to_repr}

///|
pub extend DeclarationIdentities with Eq::{not_equal, equal}

///|
pub extend EffectFlavor with @prettyprinter.Pretty::{pretty}

///|
pub extend EffectFlavor with Debug::{to_repr}

///|
pub extend EffectFlavor with Eq::{not_equal, equal}

///|
pub extend EffectSymbolId with @prettyprinter.Pretty::{pretty}

///|
pub extend EffectSymbolId with Compare::{op_lt, op_le, op_ge, compare, op_gt}

///|
pub extend EffectSymbolId with Debug::{to_repr}

///|
pub extend EffectSymbolId with Eq::{not_equal, equal}

///|
pub extend EffectSymbolMetadata with @prettyprinter.Pretty::{pretty}

///|
pub extend EffectSymbolMetadata with Debug::{to_repr}

///|
pub extend EffectSymbolMetadata with Eq::{not_equal, equal}

///|
pub extend FieldSymbolId with @prettyprinter.Pretty::{pretty}

///|
pub extend FieldSymbolId with Compare::{op_lt, op_le, op_ge, compare, op_gt}

///|
pub extend FieldSymbolId with Debug::{to_repr}

///|
pub extend FieldSymbolId with Eq::{not_equal, equal}

///|
pub extend FieldSymbolMetadata with @prettyprinter.Pretty::{pretty}

///|
pub extend FieldSymbolMetadata with Debug::{to_repr}

///|
pub extend FieldSymbolMetadata with Eq::{not_equal, equal}

///|
pub extend NominalTypeKind with @prettyprinter.Pretty::{pretty}

///|
pub extend NominalTypeKind with Debug::{to_repr}

///|
pub extend NominalTypeKind with Eq::{not_equal, equal}

///|
pub extend OperationSymbolId with @prettyprinter.Pretty::{pretty}

///|
pub extend OperationSymbolId with Compare::{op_lt, op_le, op_ge, compare, op_gt}

///|
pub extend OperationSymbolId with Debug::{to_repr}

///|
pub extend OperationSymbolId with Eq::{not_equal, equal}

///|
pub extend OperationSymbolMetadata with @prettyprinter.Pretty::{pretty}

///|
pub extend OperationSymbolMetadata with Debug::{to_repr}

///|
pub extend OperationSymbolMetadata with Eq::{not_equal, equal}

///|
pub extend SymbolId with Debug::{to_repr}

///|
pub extend SymbolId with Eq::{not_equal, equal}

///|
pub extend SymbolIdentityAllocator with Debug::{to_repr}

///|
pub extend SymbolIdentityAllocator with Eq::{not_equal, equal}

///|
pub extend SymbolMetadataArena with Debug::{to_repr}

///|
pub extend SymbolMetadataArena with Eq::{not_equal, equal}

///|
pub extend SymbolRegistry with @prettyprinter.Pretty::{pretty}

///|
pub extend SymbolRegistry with Debug::{to_repr}

///|
pub extend SymbolRegistry with Eq::{not_equal, equal}

///|
pub extend TypeAliasSymbolId with @prettyprinter.Pretty::{pretty}

///|
pub extend TypeAliasSymbolId with Compare::{op_lt, op_le, op_ge, compare, op_gt}

///|
pub extend TypeAliasSymbolId with Debug::{to_repr}

///|
pub extend TypeAliasSymbolId with Eq::{not_equal, equal}

///|
pub extend TypeAliasSymbolMetadata with @prettyprinter.Pretty::{pretty}

///|
pub extend TypeAliasSymbolMetadata with Debug::{to_repr}

///|
pub extend TypeAliasSymbolMetadata with Eq::{not_equal, equal}

///|
pub extend TypeMemberSymbolId with @prettyprinter.Pretty::{pretty}

///|
pub extend TypeMemberSymbolId with Compare::{
  op_lt,
  op_le,
  op_ge,
  compare,
  op_gt,
}

///|
pub extend TypeMemberSymbolId with Debug::{to_repr}

///|
pub extend TypeMemberSymbolId with Eq::{not_equal, equal}

///|
pub extend TypeMemberSymbolMetadata with @prettyprinter.Pretty::{pretty}

///|
pub extend TypeMemberSymbolMetadata with Debug::{to_repr}

///|
pub extend TypeMemberSymbolMetadata with Eq::{not_equal, equal}

///|
pub extend TypeParameterId with @prettyprinter.Pretty::{pretty}

///|
pub extend TypeParameterId with Compare::{op_lt, op_le, op_ge, compare, op_gt}

///|
pub extend TypeParameterId with Debug::{to_repr}

///|
pub extend TypeParameterId with Eq::{not_equal, equal}

///|
pub extend TypeParameterMetadata with @prettyprinter.Pretty::{pretty}

///|
pub extend TypeParameterMetadata with Debug::{to_repr}

///|
pub extend TypeParameterMetadata with Eq::{not_equal, equal}

///|
pub extend TypeSymbolId with @prettyprinter.Pretty::{pretty}

///|
pub extend TypeSymbolId with Compare::{op_lt, op_le, op_ge, compare, op_gt}

///|
pub extend TypeSymbolId with Debug::{to_repr}

///|
pub extend TypeSymbolId with Eq::{not_equal, equal}

///|
pub extend TypeSymbolMetadata with @prettyprinter.Pretty::{pretty}

///|
pub extend TypeSymbolMetadata with Debug::{to_repr}

///|
pub extend TypeSymbolMetadata with Eq::{not_equal, equal}

///|
pub extend ValueSymbolId with @prettyprinter.Pretty::{pretty}

///|
pub extend ValueSymbolId with Compare::{op_lt, op_le, op_ge, compare, op_gt}

///|
pub extend ValueSymbolId with Debug::{to_repr}

///|
pub extend ValueSymbolId with Eq::{not_equal, equal}

///|
pub extend ValueSymbolKind with @prettyprinter.Pretty::{pretty}

///|
pub extend ValueSymbolKind with Debug::{to_repr}

///|
pub extend ValueSymbolKind with Eq::{not_equal, equal}

///|
pub extend ValueSymbolMetadata with @prettyprinter.Pretty::{pretty}

///|
pub extend ValueSymbolMetadata with Debug::{to_repr}

///|
pub extend ValueSymbolMetadata with Eq::{not_equal, equal}

///|
pub extend ValueSymbolProvenance with Debug::{to_repr}

///|
pub extend ValueSymbolProvenance with Eq::{not_equal, equal}

///|
pub extend VariantSymbolId with @prettyprinter.Pretty::{pretty}

///|
pub extend VariantSymbolId with Compare::{op_lt, op_le, op_ge, compare, op_gt}

///|
pub extend VariantSymbolId with Debug::{to_repr}

///|
pub extend VariantSymbolId with Eq::{not_equal, equal}

///|
pub extend VariantSymbolMetadata with @prettyprinter.Pretty::{pretty}

///|
pub extend VariantSymbolMetadata with Debug::{to_repr}

///|
pub extend VariantSymbolMetadata with Eq::{not_equal, equal}
